# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Larry Reid
email: larry.reid@jadesystems.ca
description: > # this means to ignore newlines until "baseurl:"
  Home site for Phil and Larry's next adventure. Enabling your
  people to be more effective through technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lcreid.github.io" # the base hostname & protocol for your site
twitter_username: lenchoreyes
github_username:  lcreid

# Build settings
markdown: kramdown
